/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as ControlsRouteImport } from './routes/controls'
import { Route as FindingsRouteImport } from './routes/findings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ConnectorsSourceRouteImport } from './routes/connectors.$source'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsRoute = ControlsRouteImport.update({
  id: '/controls',
  path: '/controls',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsRoute = FindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsSourceRoute = ConnectorsSourceRouteImport.update({
  id: '/$source',
  path: '/$source',
  getParentRoute: () => ConnectorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/connectors': typeof ConnectorsRouteWithChildren
  '/controls': typeof ControlsRoute
  '/findings': typeof FindingsRoute
  '/projects': typeof ProjectsRoute
  '/connectors/$source': typeof ConnectorsSourceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/connectors': typeof ConnectorsRouteWithChildren
  '/controls': typeof ControlsRoute
  '/findings': typeof FindingsRoute
  '/projects': typeof ProjectsRoute
  '/connectors/$source': typeof ConnectorsSourceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/connectors': typeof ConnectorsRouteWithChildren
  '/controls': typeof ControlsRoute
  '/findings': typeof FindingsRoute
  '/projects': typeof ProjectsRoute
  '/connectors/$source': typeof ConnectorsSourceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/connectors'
    | '/controls'
    | '/findings'
    | '/projects'
    | '/connectors/$source'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/connectors'
    | '/controls'
    | '/findings'
    | '/projects'
    | '/connectors/$source'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/connectors'
    | '/controls'
    | '/findings'
    | '/projects'
    | '/connectors/$source'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  ConnectorsRoute: typeof ConnectorsRouteWithChildren
  ControlsRoute: typeof ControlsRoute
  FindingsRoute: typeof FindingsRoute
  ProjectsRoute: typeof ProjectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls': {
      id: '/controls'
      path: '/controls'
      fullPath: '/controls'
      preLoaderRoute: typeof ControlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings': {
      id: '/findings'
      path: '/findings'
      fullPath: '/findings'
      preLoaderRoute: typeof FindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors/$source': {
      id: '/connectors/$source'
      path: '/$source'
      fullPath: '/connectors/$source'
      preLoaderRoute: typeof ConnectorsSourceRouteImport
      parentRoute: typeof ConnectorsRoute
    }
  }
}

interface ConnectorsRouteChildren {
  ConnectorsSourceRoute: typeof ConnectorsSourceRoute
}

const ConnectorsRouteChildren: ConnectorsRouteChildren = {
  ConnectorsSourceRoute: ConnectorsSourceRoute,
}

const ConnectorsRouteWithChildren = ConnectorsRoute._addFileChildren(
  ConnectorsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  ConnectorsRoute: ConnectorsRouteWithChildren,
  ControlsRoute: ControlsRoute,
  FindingsRoute: FindingsRoute,
  ProjectsRoute: ProjectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
